version: "3.9"
services:
  pg:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mk
      POSTGRES_DB: mktracker
